### ISSUE TITLE
Idea: Fetch default values from Mix config

### ISSUE THREAD

**Issue by h4cc** [asaaki/flasked#2]
In my current projects we use a mixture of Mix config and System Env.

How about enabling flasked to use the values from `config.exs` as defaults too?

That way we could use the default Mix config system but being abled to overwrite values using System ENV if needed.

**Comment by asaaki** [comment]
Sounds like a nice idea.
Not sure if I can do this any time soon.

**Comment by asaaki** [comment]
No active development.
